-- Databricks notebook source
-- MAGIC %md
-- MAGIC ### Example Exploratory Notebook
-- MAGIC
-- MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
-- MAGIC
-- MAGIC **Note**: This notebook is not executed as part of the pipeline.

-- COMMAND ----------

USE CATALOG `dev`;
USE SCHEMA `naval_bronze`;

-- COMMAND ----------

SELECT * from samples.wanderbricks.users

-- COMMAND ----------

drop table dev.naval_silver.sales_cleaned_pl
